[tool.poetry]
name = "aws-config-rule-fixer"
version = "0.1.0"
description = ""
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.34.13"
pydantic = "^2.5.3"
click = "^8.1.7"
loguru = "^0.7.2"
questionary = "^2.0.1"

[tool.poetry.scripts]
"s3-bucket-ssl-requests-only" = "aws_config_rule_fixer.s3_bucket_ssl_requests_only:main"
"ec2-ebs-encryption-by-default" = "aws_config_rule_fixer.ec2_ebs_encryption_by_default:main"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.11"
mypy = "^1.8.0"
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
